#server:
#  port: 8080
#  servlet:
#    context-path: /api
#
#springdoc:
#  swagger-ui:
#    url: http://localhost:8080/api/swagger-ui.html

spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect