springdoc:
  api-docs:
    path: /docs
  swagger-ui:
    path: /swagger
    operationsSorter: method

server:
  servlet:
    context-path: /api/v1

spring:
  application:
    name: api-bank
  jpa:
    hibernate:
      ddl-auto: none
    show_sql: false
    defer-datasource-initialization: true
    database: postgresql
  datasource:
    url: jdbc:postgresql://localhost:5432/Bank
    username: postgres
    password: ${DB_PASS}
    driver-class-name: org.postgresql.Driver